// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpjjgzmvchcfnkyssrpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwampnem12Y2hjZm5reXNzcnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzOTIzMjEsImV4cCI6MjA1Mzk2ODMyMX0.W2E3tmhsFBJyFW_y4rfZ2eQfnLT7JgsnOOY8xff3lP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);